/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
void sub_AA0();
// int strcasecmp(const char *s1, const char *s2);
// char *strncpy(char *dest, const char *src, size_t n);
// int puts(const char *s);
// char *inet_ntoa(struct in_addr in);
// char *strchr(const char *s, int c);
// int pclose(FILE *stream);
// unsigned int alarm(unsigned int seconds);
// size_t strcspn(const char *s, const char *reject);
// char *fgets(char *s, int n, FILE *stream);
// __sighandler_t signal(int sig, __sighandler_t handler);
// __int64 __gmon_start__(void); weak
// int inet_aton(const char *cp, struct in_addr *inp);
// int _IO_getc(_IO_FILE *fp);
// __int64 __fastcall __printf_chk(_QWORD, _QWORD); weak
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// FILE *popen(const char *command, const char *modes);
// void __noreturn exit(int status);
// __int64 __fastcall __cxa_finalize(_QWORD); weak
// __int64 __fastcall __sprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
__int64 (**sub_C30())(void);
__int64 sub_C60();
__int64 (**sub_CA0())(void);
__int64 sub_CE0();
void __noreturn handler();
__int64 sub_D3A();
signed __int64 __fastcall sub_D65(char *a1, _BYTE *a2);
_BOOL8 __fastcall sub_DCC(const char *a1);
unsigned __int64 __fastcall sub_E35(char *a1);
unsigned __int64 __fastcall sub_F5C(char *a1);
unsigned __int64 __fastcall sub_10BD(char *a1);
__int64 __fastcall main(__int64 a1, char **a2, char **a3);
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 __fastcall Jv_RegisterClasses(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

int dword_0 = 1179403647; // weak
char aWelcomeToAnoth[21] = "\nWelcome to another K"; // idb
__int64 (__fastcall *off_201DE0[2])() = { &sub_CE0, &sub_CA0 }; // weak
__int64 (__fastcall *off_201DE8)() = &sub_CA0; // weak
__int64 qword_201DF0 = 0LL; // weak
void *off_2020C8 = &off_2020C8; // weak
char edata; // weak
_UNKNOWN unk_2020D7; // weak
// extern struct _IO_FILE *stdout;
// extern struct _IO_FILE *stdin;
// extern _UNKNOWN _cxa_finalize; weak
// extern _UNKNOWN _gmon_start__; weak


//----- (0000000000000A80) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    result = (void *)__gmon_start__();
  return result;
}
// B70: using guessed type __int64 __gmon_start__(void);

//----- (0000000000000AA0) ----------------------------------------------------
void sub_AA0()
{
  JUMPOUT(&dword_0);
}
// 0: using guessed type int dword_0;

//----- (0000000000000C00) ----------------------------------------------------
#error "C06: positive sp value has been found (funcsize=3)"

//----- (0000000000000C30) ----------------------------------------------------
__int64 (**sub_C30())(void)
{
  __int64 (**result)(void); // rax

  result = (__int64 (**)(void))(&unk_2020D7 - (_UNKNOWN *)&edata);
  if ( (unsigned __int64)(&unk_2020D7 - (_UNKNOWN *)&edata) > 0xE )
  {
    result = &ITM_deregisterTMCloneTable;
    if ( &ITM_deregisterTMCloneTable )
      result = (__int64 (**)(void))ITM_deregisterTMCloneTable();
  }
  return result;
}
// 2020D0: using guessed type char edata;
// 202190: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (0000000000000C60) ----------------------------------------------------
__int64 sub_C60()
{
  return 0LL;
}

//----- (0000000000000CA0) ----------------------------------------------------
__int64 (**sub_CA0())(void)
{
  __int64 (**result)(void); // rax

  if ( !edata )
  {
    if ( &_cxa_finalize )
      __cxa_finalize(off_2020C8);
    result = sub_C30();
    edata = 1;
  }
  return result;
}
// BE0: using guessed type __int64 __fastcall __cxa_finalize(_QWORD);
// 2020C8: using guessed type void *off_2020C8;
// 2020D0: using guessed type char edata;

//----- (0000000000000CE0) ----------------------------------------------------
__int64 sub_CE0()
{
  if ( !qword_201DF0 || !&Jv_RegisterClasses )
    return sub_C60();
  Jv_RegisterClasses(&qword_201DF0);
  return sub_C60();
}
// 201DF0: using guessed type __int64 qword_201DF0;
// 2021A0: using guessed type __int64 __fastcall Jv_RegisterClasses(_QWORD);

//----- (0000000000000D20) ----------------------------------------------------
void __noreturn handler()
{
  puts("Too long, closing.");
  exit(1);
}

//----- (0000000000000D3A) ----------------------------------------------------
__int64 sub_D3A()
{
  puts("Commands: ping, dig, host, exit");
  return __printf_chk(1LL, ": ");
}
// BA0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD);

//----- (0000000000000D65) ----------------------------------------------------
signed __int64 __fastcall sub_D65(char *a1, _BYTE *a2)
{
  char v2; // al

  v2 = *a1;
  if ( !*a1 )
  {
LABEL_10:
    *a2 = 0;
    return 1LL;
  }
  while ( v2 == 32 )
  {
LABEL_9:
    v2 = *++a1;
    if ( !*a1 )
      goto LABEL_10;
  }
  if ( (unsigned __int8)(v2 - 38) <= 1u )
    return 0LL;
  if ( v2 == 124 )
    return 0LL;
  if ( v2 == 42 )
    return 0LL;
  if ( (v2 & 0xFD) == 33 )
    return 0LL;
  if ( (unsigned __int8)(v2 - 58) > 1u )
  {
    *a2++ = v2;
    goto LABEL_9;
  }
  return 0LL;
}

//----- (0000000000000DCC) ----------------------------------------------------
_BOOL8 __fastcall sub_DCC(const char *a1)
{
  unsigned __int64 v1; // rcx
  _BOOL8 result; // rax
  char v3; // dl

  v1 = strlen(a1) + 1;
  result = 0LL;
  if ( v1 - 4 <= 0x3C )
  {
    if ( (unsigned __int8)((*a1 & 0xDF) - 65) <= 0x19u || (result = 0LL, (unsigned __int8)(*a1 - 48) <= 9u) )
    {
      v3 = a1[v1 - 2];
      result = 1LL;
      if ( (unsigned __int8)((v3 & 0xDF) - 65) > 0x19u )
        result = (unsigned __int8)(v3 - 48) <= 9u;
    }
  }
  return result;
}

//----- (0000000000000E35) ----------------------------------------------------
unsigned __int64 __fastcall sub_E35(char *a1)
{
  char *v1; // rax
  FILE *v2; // rbp
  struct in_addr in; // [rsp+0h] [rbp-538h]
  char command; // [rsp+10h] [rbp-528h]
  char cp; // [rsp+190h] [rbp-3A8h]
  char s; // [rsp+310h] [rbp-228h]
  unsigned __int64 v8; // [rsp+518h] [rbp-20h]

  v8 = __readfsqword(0x28u);
  if ( a1 )
  {
    if ( (unsigned int)sub_D65(a1, &cp) )
    {
      if ( inet_aton(&cp, &in) )
      {
        v1 = inet_ntoa(in);
        __sprintf_chk(&command, 1LL, 384LL, "ping -c 3 -W 3 %s", v1);
        v2 = popen(&command, "r");
        if ( v2 )
        {
          while ( fgets(&s, 512, v2) )
            __printf_chk(1LL, &s);
          pclose(v2);
        }
        else
        {
          puts("Command failed.");
        }
      }
      else
      {
        puts("Invalid IP address.");
      }
    }
    else
    {
      puts("Invalid IP address sent to ping.");
    }
  }
  else
  {
    puts("No address specified.");
  }
  return __readfsqword(0x28u) ^ v8;
}
// BA0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD);
// BF0: using guessed type __int64 __fastcall __sprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000F5C) ----------------------------------------------------
unsigned __int64 __fastcall sub_F5C(char *a1)
{
  char *v1; // rax
  FILE *v2; // rbp
  struct in_addr in; // [rsp+0h] [rbp-538h]
  char command; // [rsp+10h] [rbp-528h]
  char cp; // [rsp+190h] [rbp-3A8h]
  char s; // [rsp+310h] [rbp-228h]
  unsigned __int64 v8; // [rsp+518h] [rbp-20h]

  v8 = __readfsqword(0x28u);
  if ( a1 )
  {
    if ( (unsigned int)sub_D65(a1, &cp) )
    {
      if ( inet_aton(&cp, &in) )
      {
        v1 = inet_ntoa(in);
        __sprintf_chk(&command, 1LL, 384LL, "dig -x %s", v1);
      }
      else
      {
        if ( !(unsigned int)sub_DCC(&cp) )
        {
          puts("Invalid hostname.");
          return __readfsqword(0x28u) ^ v8;
        }
        __sprintf_chk(&command, 1LL, 384LL, "dig '%s'", &cp);
      }
      v2 = popen(&command, "r");
      if ( v2 )
      {
        while ( fgets(&s, 512, v2) )
          __printf_chk(1LL, &s);
        pclose(v2);
      }
      else
      {
        puts("Command failed.");
      }
    }
    else
    {
      puts("Invalid Host or IP address sent to dig.");
    }
  }
  else
  {
    puts("No address specified.");
  }
  return __readfsqword(0x28u) ^ v8;
}
// BA0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD);
// BF0: using guessed type __int64 __fastcall __sprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000010BD) ----------------------------------------------------
unsigned __int64 __fastcall sub_10BD(char *a1)
{
  char *v1; // rax
  FILE *v2; // rbp
  struct in_addr in; // [rsp+0h] [rbp-538h]
  char command; // [rsp+10h] [rbp-528h]
  char cp; // [rsp+190h] [rbp-3A8h]
  char s; // [rsp+310h] [rbp-228h]
  unsigned __int64 v8; // [rsp+518h] [rbp-20h]

  v8 = __readfsqword(0x28u);
  if ( a1 )
  {
    if ( (unsigned int)sub_D65(a1, &cp) )
    {
      if ( inet_aton(&cp, &in) )
      {
        v1 = inet_ntoa(in);
        __sprintf_chk(&command, 1LL, 384LL, "host %s", v1);
      }
      else
      {
        if ( !(unsigned int)sub_DCC(&cp) )
        {
          puts("Invalid hostname.");
          return __readfsqword(0x28u) ^ v8;
        }
        __sprintf_chk(&command, 1LL, 384LL, "host \"%s\"", &cp);
      }
      v2 = popen(&command, "r");
      if ( v2 )
      {
        while ( fgets(&s, 512, v2) )
          __printf_chk(1LL, &s);
        pclose(v2);
      }
      else
      {
        puts("Command failed.");
      }
    }
    else
    {
      puts("Invalid Host or IP address sent to dig.");
    }
  }
  else
  {
    puts("No address specified.");
  }
  return __readfsqword(0x28u) ^ v8;
}
// BA0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD);
// BF0: using guessed type __int64 __fastcall __sprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000000121E) ----------------------------------------------------
__int64 __fastcall main(__int64 a1, char **a2, char **a3)
{
  __int64 v3; // rbx
  int v4; // ebp
  int v5; // eax
  int v6; // ebx
  char *v7; // rbx
  char v9[272]; // [rsp+0h] [rbp-258h]
  char dest[264]; // [rsp+110h] [rbp-148h]
  unsigned __int64 v11; // [rsp+218h] [rbp-40h]

  v11 = __readfsqword(0x28u);
  setvbuf(stdout, 0LL, 2, 0LL);
  signal(14, (__sighandler_t)handler);
  alarm(0x2Du);
  puts(aWelcomeToAnoth);
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        sub_D3A();
        v3 = 0LL;
        v4 = 0;
        do
        {
          v5 = _IO_getc(stdin);
          if ( v5 == -1 )
            break;
          if ( v5 == 10 )
            break;
          ++v4;
          v9[v3] = v5;
          v3 = v4;
        }
        while ( (unsigned __int64)v4 <= 0xFE );
        v9[v3] = 0;
        if ( v3 )
          break;
        puts("Command not recognized??");
      }
      v6 = strcspn(v9, " ");
      strncpy(dest, v9, v6);
      dest[v6] = 0;
      if ( v6 > 0 )
        break;
      puts("No parameters sent?");
    }
    if ( !strcasecmp(dest, "exit") )
      break;
    if ( !strcasecmp(dest, "?") )
    {
      sub_D3A();
    }
    else if ( !strcasecmp(dest, "help") )
    {
      sub_D3A();
    }
    else
    {
      v7 = strchr(v9, 32);
      if ( v7 )
      {
        if ( !strcasecmp(dest, "ping") )
        {
          sub_E35(v7);
        }
        else if ( !strcasecmp(dest, "dig") )
        {
          sub_F5C(v7);
        }
        else if ( !strcasecmp(dest, "host") )
        {
          sub_10BD(v7);
        }
        else
        {
          puts("Unknown command");
        }
      }
      else
      {
        puts("No parameters sent for command.");
      }
    }
  }
  puts("Goodbye");
  return 0LL;
}
// 121E: using guessed type char dest[264];
// 121E: using guessed type char var_258[272];

//----- (0000000000001450) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13
  __int64 v4; // rbx
  signed __int64 v5; // rbp

  v3 = a3;
  v4 = 0LL;
  v5 = &off_201DE8 - off_201DE0;
  init_proc();
  if ( v5 )
  {
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))off_201DE0[v4++])(a1, a2, v3);
    while ( v4 != v5 );
  }
}
// 201DE0: using guessed type __int64 (__fastcall *off_201DE0[2])();
// 201DE8: using guessed type __int64 (__fastcall *off_201DE8)();

//----- (00000000000014C4) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 17 function(s)"
